
<?php
$this->headScript()->prependFile($this->basePath() . '/assets/js/main.js')
        ->prependFile($this->basePath() . '/assets/lib/touch-punch/jquery.ui.touch-punch.min.js')
        ->prependFile($this->basePath() . '/assets/lib/tablesorter/js/jquery.tablesorter.min.js')
        ->prependFile($this->basePath() . '/assets/lib/datatables/DT_bootstrap.js')
        ->prependFile($this->basePath() . '/assets/lib/datatables/jquery.dataTables.js');
?>
<div id="top"><?= $this->partial('layout/admin_top_menu', array('tittle' => 'Order List')); ?></div>
<div id="left"> <?= $this->partial('layout/left-menu', array('products' => 'active')); ?></div> 
<div id="content"> 
    <div class="outer">
        <div class="inner">
            <!--/span-->
            <div class="row">
                <div class="col-lg-12">
                    <div class="box">
                        <header>
                            <h5><form name="categoryform" method="POST" action="" >
                                    <select onchange="this.form.submit()" name="category_id"  class="form-control">
                                        <option value=''>All</option>
                                        <?php foreach ($this->categories as $category) { ?>
                                            <option <?php if ($category['value'] == $this->category) { ?> selected <?php } ?> value="<?php echo $category['value'] ?>"><?php echo $category['label'] ?></option>
                                        <?php } ?>
                                    </select>
                                </form></h5>                           
                        </header>
                        <div id="collapse4" class="body">
                            <form name="dataform" method="POST" action="">

                                <div class="action">                                    
                                    <select name="action" class="form-control">
                                        <option value="">Select Action</option>
                                        <option value="multidelete">Delete</option>                                        
                                    </select>
                                    <input type="submit" value="Submit" class="btn btn-default btn-sm"/>
                                </div>
                                <table id="dataTable" class="table ">
                                    <thead>
                                        <tr>
                                            <th><input type="checkbox" name="sellectall" value="" ></th>
                                            <th>Product </th>
                                            <th>User </th>
                                            <th>Quantity </th>
                                            <th>Amount </th>
                                            <th>&nbsp;</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->paginator as $product) : ?>
                                            <tr>
                                                <td>

                                                    <input type="checkbox" class="case" name="ids[]" value="<?php echo $product->id ?>"></td>
                                                <td>                                                    
                                                    <?php echo $this->escapeHtml($product->title); ?>
                                                </td>
                                                <td>                                                    
                                                    <?php echo $this->escapeHtml($product->user); ?>
                                                </td>
                                                <td>                                                    
                                                    <?php echo $this->escapeHtml($product->total_quantity); ?>
                                                </td>
                                                 <td>                                                    
                                                    <?php echo $this->escapeHtml($product->total_amount); ?>
                                                </td>
                                                <td>
                                                     <a href="<?php echo $this->url('admin/orders', array('action' => 'view', 'id' => $product->id));
                                                    ?>"><i class="fa fa-pencil fa-fw"></i></a>
                                                    <a href="<?php echo $this->url('admin/orders', array('action' => 'delete', 'id' => $product->id));
                                                    ?>"><i class="fa fa-trash-o fa-fw"></i></a>

                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </form>
                        </div></div>
                </div>
                <!--/row-->
            </div>
            <!--/span-->
        </div>
        <!--/row-->
    </div>
    <?php $this->inlineScript()->captureStart() ?>
    $(function() { metisTable(); metisSortable();});
    <?php $this->inlineScript()->captureEnd() ?>

</div> 
