<div id="top"><?= $this->partial('layout/admin_top_menu', array('tittle' => 'Edit List')); ?></div>
<div id="left"> <?= $this->partial('layout/left-menu', array('find' => 'active')); ?></div> 
<div id="content"> 
    <div class="outer">
        <div class="inner">
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('admin/products', array('action' => 'edit', 'id' => $this->product->id)));
            $form->prepare();

            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id'));
            echo $this->formLabel($form->get('category_id'));
            echo $this->formSelect($form->get('category_id'));
            echo $this->formRow($form->get('title'));
            echo $this->formRow($form->get('description'));
            echo $this->formRow($form->get('sku'));
            echo $this->formRow($form->get('price'));
            echo $this->formRow($form->get('quantity'));
            echo $this->formLabel($form->get('product_image'));
            echo $this->formFile($form->get('product_image'));
            ?>
            <img src="<?php echo $this->basePath('/../module/CremationPlan/assets/product/thumb/'.$this->product->id.'_'.$this->product->product_image); ?>" width="72" height="72"/>
            <?php
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>