  <?= $this->partial('layout/top_links'); ?>

<?php if ($this->message != '') { ?>

    <div class="flash_message">

        <?php echo $this->message[0]; ?>

    </div>

<?php } ?>

<?php echo 'sdf' . $this->id; ?>



<a href="#" class="btn btn-lg btn-default">

    Memoralize

</a>

<div class="memorial">



    <h2>Create a permanent memorial site</h2>

    <div class="steps"  <?php if ($this->step == 0) {

    

} else { ?> style="pointer-events: none;" <?php } ?>>

        <h3> step 1</h3>

        <p>

            <a  href="<?php echo $this->url('memoralize-create-infos') ?>"> add information</a>

        </p>

    </div>

    <div class="steps" <?php if ($this->step == 1) {

    

} else { ?> style="pointer-events: none;" <?php } ?>>

        <h3>step 2</h3>

        <p>

            <a  href="<?php echo $this->url('memoralize-create-media', array('id' => $this->id, 'step' => 1)) ?>"> add video</a>

        </p>

    </div>

    <div class="steps" <?php if ($this->step == 2) {

    

} else { ?> style="pointer-events: none;" <?php } ?>>

        <h3>step 3</h3>

        <p>

            <a  href="<?php echo $this->url('memoralize-create-themes', array('id' => $this->id, 'step' => 2)) ?>"> add themes</a>

        </p>

    </div>

    <div class="steps" <?php if ($this->step == 3) {

    

} else { ?> style="pointer-events: none;" <?php } ?>>

        <h3>step 4</h3>

        <p>

        <form method="post" action="<?php echo $this->url('compose-mail') ?>">

            <input  type="hidden" name="subject" value="Memoralize"/>

            <input  type="hidden" name="action" value="share"/>

            <input  type="hidden" name="msg" value="<?php echo $this->url('memoralize-create', array('id' => $this->id)); ?>"/>

            <input  type="submit" value="send to friends"/>

        </form>

            </p>

    </div>

</div>