<div id="top"><?= $this->partial('layout/admin_top_menu', array('tittle' => 'Edit List')); ?></div>
<div id="left"> <?= $this->partial('layout/left-menu', array('preplanning' => 'active')); ?></div> 
<div id="content"> 
    <div class="outer">
        <div class="inner">
            <?php if ($this->message != '') { ?>
                <div class="error_message">
                    <?php echo $this->message[0]; ?>
                </div>
            <?php } ?>
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('admin/pre-planning', array('action' => 'editchecklist','category'=>$this->category, 'id' => $this->item->id)));
            $form->prepare();

            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id'));
            echo $this->formHidden($form->get('preplanning_id'));
          
            echo $this->formRow($form->get('title'));
               
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>