<?php

// Generated by ZF2's ./bin/classmap_generator.php @ Sun, 15 Jan 2012 19:46:42 -0700
return array(
    'EventCalendar\Module' => __DIR__ . '/src/EventCalendar/Module.php',
    'EventCalendar\Mapper\Events' => __DIR__ . '/src/EventCalendar/Mapper/Events.php',
    'EventCalendar\Mapper\EventsInterface' => __DIR__ . '/src/EventCalendar/Mapper/EventsInterface.php',
    'EventCalendar\Controller\EventsController' => __DIR__ . '/src/EventCalendar/Controller/EventsController.php',
    'EventCalendar\Service\ModuleOptionsFactory' => __DIR__ . '/src/EventCalendar/Service/ModuleOptionsFactory.php',
    'EventCalendar\Service\EventsMapperFactory' => __DIR__ . '/src/EventCalendar/Service/EventsMapperFactory.php',
    'EventCalendar\Options\ModuleOptions' => __DIR__ . '/src/EventCalendar/Options/ModuleOptions.php',
    'EventCalendar\Entity\Events' => __DIR__ . '/src/EventCalendar/Entity/Events.php',
    'EventCalendar\Entity\EventsInterface' => __DIR__ . '/src/EventCalendar/Entity/EventsInterface.php',
);