<?php
$title = 'Documents';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->paginator as $document) : // <-- change here! ?>
        <tr>
            <td><?php echo $document->profilename;?></td>
            <td><?php echo $document->profiletype;?></td>
            <td>
                <a href="<?php echo $this->url('documents',
                    array('action' => 'edit', 'id' => $document->id));?>">Edit</a>
                <a href="<?php echo $this->url('documents',
                    array('action' => 'delete', 'id' => $document->id));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?php // add at the end of the file after the table
echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    array('partial/paginator.phtml', 'Album'),
    // the route to link to when a user clicks a control link
    array(
        'route' => 'album'
    )
);
?>