<?php
$this->headLink()
        ->prependStylesheet($this->basePath() . '/assets/lib/timepicker/css/bootstrap-timepicker.css')
        ->prependStylesheet($this->basePath() . '/assets/css/rituals.css');

$this->headScript()->prependFile($this->basePath() . '/assets/lib/timepicker/js/bootstrap-timepicker.min.js');
?>
<div class="container">
<?php echo $this->partial('layout/top_links'); ?>


<div class="layout_nav">
        <ul>
            <li><a class="before" href="<?php echo $this->basePath('/'); ?>">Home &rsaquo; </a></li>
             <li><a class="before" href="<?php echo $this->url('cremation-plans'); ?>">Cremation Planning &rsaquo;</a></li>
            <li><a class="before" href="<?php echo $this->url('event-calendar-events'); ?>">Events &rsaquo;</a></li> 
            <li>Add Event</li> 
        </ul>
 </div>

<div class='clear'></div>

<div class="col-md-4 col-sm-5 col-xs-5">
<div class="eventmenu" data-role="content" > 
    <select name="create" id="create" class="form-control">
        <option value="">Select</option>
         <option value="event" selected="selected">Create Event</option>
        <option value="viewevent">View Event</option>
    </select>
    <div class="datepicker"></div>
    <ul>       

        <li class="active"><a href="<?php echo $this->url('event-calendar-events'); ?>">My Calendar</a></li>
        <li><a href="<?php echo $this->url('event-calendar-events', array('action' => 'in')); ?>">Indian Holidays</a></li>  
        <li><a href="<?php echo $this->url('event-calendar-events', array('action' => 'us')); ?>">US Holidays</a></li> 
    </ul>
</div>
</div>
	<div class="col-md-8 col-sm-7 col-xs-7 event-block">
    <div class="eventmain">
    <?php
    $title = 'Add new Event';
    $this->headTitle($title);
    $form = $this->form;
    $form->setAttribute('action', $this->url('event-calendar-events', array('action' => 'add')));
    $form->prepare();

    echo $this->form()->openTag($form);
    ?>
    	<div  class="obituary-creation1">
        <label style="margin-top:0px">Profile Type</label>
        <select id="profile_type" name="profile_type" class="form-control" >
            <option value="">Select</option>
            <option value="cremationplan">Cremation Plan</option>
            <option value="preplanning">Pre Planning</option>
            <option <?php if($this->type=='obituary'){ echo 'selected';}?> value="obituary">Obituary</option>
            <option <?php if($this->type=='memoralize'){ echo 'selected';}?> value="memoralize">Memoralize</option>
			 <option value="preplanning">iMandir</option>
			 <option value="preplanning">Anniversary</option>
			 <option value="preplanning">Special Event</option>
        </select>
        </div>

    	<div  class="obituary-creation2" id="profileField">
        <label>Profile Name</label>
        <!--<select id="profile_id" name="profile_id" class="form-control">-->
        <input type="text" id="profile_id" name="profile_id" class="form-control">
        <!--</select>-->            
		</div> 
        <div class="clear"> </div>  
        
        <div  class="obituary-creation12"> 
        <label>Title</label>
        <input type="text" id="title" name="title" class="form-control"/>        
        </div>
        
        <div class="clear"> </div>
        
        <div  class="obituary-creation1">
        <label>Date</label>
        <input type="text" id="dp1" name="edate" placeholder= 'dd/mm/yyyy' class="form-control dp"/>
        </div>
        
        <div class="obituary-creation2" >
        <div  class="obituary-creation1" > 
        <label>Start Time</label>
        <input type="text" id="start_time" name="start_time" class="form-control timepicker-default"/>
        </div>
        
        <div  class="obituary-creation1" style="float:right" > 
        <label>End Time</label>
        <input type="text" id="end_time" name="end_time" class="form-control timepicker-default"/>
        </div>
        </div>
		<div class="clear"> </div>
        
        <div  class="obituary-creation1"> 
          <label> Location </label>
        <input type="text" id="location" name="location" class="form-control"/>     
        </div>
        
        <div  class="obituary-creation2"> 
          <label> Contact </label>
        <input type="text" id="contact" name="contact" class="form-control"/>     
        </div>

        <div class="clear"> </div>
                
        <div  class="obituary-creation100"> 
          <label> Content </label>
        <textarea type="text" id="nicedit" name="content" class="form-control"> </textarea>     
        </div>
        
        <div  class="obituary-creation2"> </div>
        
        <div class="clear"> </div>
        <div class="add-btn-block">
        <input id="submitbutton" class="btn btn-lg btn-primary btn-block" type="submit" value="Add" name="submit">
        </div>
        
    <?php
    //echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>
</div>
</div>
<form id="eventadd" method="GET">
</form>
<script>

    $(function() {

        $('.dp').datepicker({
            format: 'yyyy-mm-dd'
        });
        $('.timepicker-default').timepicker();


        $(".datepicker").datepicker(
			{
				onSelect: function(dateText, inst) { 
				//alert(dateText);
				var url = "<?php echo $this->url('event-calendar-events'); ?>";
        			window.location = url+'?edate=' + dateText;
    			}			
			}        
        );
                

        $('#profile_type').change(function(e) {
            var taskUrl;

            if ($(this).val() == 'obituary') {
					
                taskUrl = '<?php echo $this->url('sharedtasks', array('action' => 'obituarytasks')); ?>';
            } else if ($(this).val() == 'memoralize') {

                taskUrl = '<?php echo $this->url('sharedtasks', array('action' => 'memoralizetasks')); ?>';
            }else {
            	$("#profileField").empty();
					$("#profileField").append("<label>Profile Name</label><input type='text' id='profile_id' name='profile_id' class='form-control'/>");

            	return;
            }
            var data = {
                'user_id': '<?php echo $this->userid; ?>',
            }

            $.ajax({
                type: 'POST',
                url: taskUrl,
                data: data,
                success: function(data) {
						$("#profileField").empty();
						$("#profileField").append("<label>Profile Name</label><select id='profile_id' name='profile_id' class='form-control'>");
						
                    $('#profile_id').html(data);

                }
            });
        });
        <?php if($this->type=='obituary'){ echo "$('#profile_type').trigger('change');";}?>
   
   setTimeout(function(){
       $("#profile_id").val('<?php echo $this->id;?>');
   },1000);
    });
	$(document).ready(function() {
$("#create").change(function() {
//alert()
            if ($(this).val() == 'event') {               
                //var url = '<?php echo $this->url('event-calendar-events', array('action' => 'add','type'=>$this->type,'id'=>$this->id)); ?>';
				var url = '<?php echo $this->url('event-calendar-events', array('action' => 'add')); ?>';
               $('#eventadd').attr('action',url);
               $('#eventadd').submit();
            }
			if ($(this).val() == 'viewevent') {                
               var url = '<?php echo $this->url('event-calendar-events'); ?>';
               //alert(url);
               $('#eventadd').attr('action',url);
               $('#eventadd').submit();
            }
        });
	});
            
        
</script>