<?php
$this->headLink()->prependStylesheet($this->basePath() . '/assets/lib/datepicker/css/datepicker.css')
        ->prependStylesheet($this->basePath() . '/assets/lib/timepicker/css/bootstrap-timepicker.css');

$this->headScript()->prependFile($this->basePath() . '/assets/lib/timepicker/js/bootstrap-timepicker.min.js')
        ->prependFile($this->basePath() . '/assets/lib/datepicker/js/bootstrap-datepicker.js');
?>
<?= $this->partial('layout/top_links'); ?>
<header class="head">
    <div class="search-bar">
        <a data-original-title="Show/Hide Menu" data-placement="bottom" data-tooltip="tooltip" class="accordion-toggle btn btn-primary btn-sm visible-xs" data-toggle="collapse" href="#menu" id="menu-toggle">
            <i class="fa fa-resize-full"></i>
        </a>
        <h3><i class="fa fa-home"></i> Edit Event</h3>

    </div>
    <!-- ."main-bar -->

</header>
<div id="left" data-role="content" >

    <ul id="menu" class="collapse">
        <li class="nav-header">Menu</li>

        <li>
            <a href="<?php echo $this->url('event-calendar-events', array('action' => 'add')); ?>">
                Add Event
            </a>
        </li> 
        <li><a href="<?php echo $this->url('event-calendar-events'); ?>">My Events</a></li>
        <li><a href="<?php echo $this->url('event-calendar-events', array('action' => 'in')); ?>">Indian Holidays</a></li>  
        <li><a href="<?php echo $this->url('event-calendar-events', array('action' => 'us')); ?>">US Holidays</a></li> 


    </ul>

</div>
<div style="width:80%;float:left">
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('event-calendar-events', array('action' => 'edit', 'id' => $this->id)));
            $form->prepare();

            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id'));
            echo $this->formRow($form->get('title'));
            
            echo $this->formRow($form->get('start'));
            echo $this->formRow($form->get('start_time'));
            echo $this->formRow($form->get('end'));
            echo $this->formRow($form->get('end_time'));
            
            echo $this->formRow($form->get('content'));
             echo $this->formHidden($form->get('user_id'));
           
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
            ?>
        </div>
   
<?php $this->inlineScript()->captureStart() ?>
$(function() {
        $('.dp').datepicker({
            format: 'yyyy-mm-dd'
        });
        $('.timepicker-default').timepicker();
    });

<?php $this->inlineScript()->captureEnd() ?>