
<?php
$this->headLink()
        ->prependStylesheet($this->basePath() . '/assets/lib/fullcalendar-1.6.2/fullcalendar/fullcalendar.css')->prependStylesheet($this->basePath() . '/assets/css/rituals.css');

$this->headScript()->prependFile($this->basePath() . '/assets/js/main.js')
        ->prependFile($this->basePath() . '/assets/lib/fullcalendar-1.6.2/fullcalendar/gcal.js')
        ->prependFile($this->basePath() . '/assets/lib/fullcalendar-1.6.2/fullcalendar/fullcalendar.min.js');
?>
  <?= $this->partial('layout/top_links'); ?>
  <div class="layout_nav" id="brecurmsdiv">
        <ul>
          <!--   <li><a class="before" href="<?php //echo $this->basePath('/'); ?>">Home &rsaquo; </a></li> -->
             <li id="menu_bredcurms"><a class="before" href="<?php echo $this->url('cremation-plans'); ?>">Cremation Planning &rsaquo;</a></li>
            <li><a class="before" href="<?php echo $this->url('event-calendar-events'); ?>">Events &rsaquo;</a></li> 
            <li>Indian Holidays</li>
        </ul>
 </div>
 <div class="clear"></div>
<?php if ($this->message != '') { ?>
    <div class="flash_message">
        <?php echo $this->message[0]; ?>
    </div>
<?php } ?>

<script>
$(document).ready(function() {
	$( ".datepicker" ).datepicker();
		$('#calendar').fullCalendar({
		
			// US Holidays
			events: 'http://www.google.com/calendar/feeds/indian__en%40holiday.calendar.google.com/public/basic',
			
			eventClick: function(event) {
				// opens events in a popup window
				window.open(event.url, 'gcalevent', 'width=700,height=600');
				return false;
			},
			
			loading: function(bool) {
				if (bool) {
					$('#loading').show();
				}else{
					$('#loading').hide();
				}
			}
			
		});
		
	});

</script>

<div class="eventmenu" data-role="content" > 
<div style="position: absolute;display: inline-block;">
    <select name="create" id="create">
         <option value="">Create</option>
        <option value="event">Event</option>
    </select>
    <div class="datepicker"></div>
    <ul>       
         
        <li><a href="<?php echo $this->url('event-calendar-events'); ?>">My Calendar</a></li>
        <li class="active"><a href="<?php echo $this->url('event-calendar-events', array('action' => 'in')); ?>">Indian Holidays</a></li>  
        <li><a href="<?php echo $this->url('event-calendar-events', array('action' => 'us')); ?>">US Holidays</a></li> 
   </ul>
</div>
  

  <div class="eventmain">
    <iframe src="https://calendar.google.com/calendar/embed?src=en.indian%23holiday%40group.v.calendar.google.com&ctz=Asia/Calcutta" style="border: 0;margin-left: 280px;" width="800" height="600" frameborder="0" scrolling="no"></iframe>
</div>
</div>
 