
<?php 
echo $this->headScript()->prependFile($this->basePath('addthis/editor/tinymce/tinymce.min.js')); ?>
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    theme: "modern",
    width: "400",
    height: "200",
    plugins: [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    toolbar2: "print preview media | forecolor backcolor emoticons",
    image_advtab: true,
    templates: [
        {title: 'Edit Blog', content: 'Test 1'},
        {title: 'Test template 2', content: 'Test 2'}
    ]
});
</script>
<section class="content">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="box">
                                <div class="box-header">
                                    <h3 class="box-title"><?php echo $this->translate('Edit Page') ?></h3> 
                                  </div><!-- /.box-header -->
                                <div class="box-body table-responsive">
                                <?php echo $this->form()->openTag($form);?> 
                        
                           <div class="form-group">
                                <div class="input-group">
                                     <label>TITLE</label>
                                    <?php echo $this->formRow($form->get('title')->setValue( $page->title));?>
								</div>
							</div>
							<div class="form-group">
                                <div class="input-group">
                                    <?php echo $this->formRow($form->get('alias')->setValue( $page->alias));?>
								</div>
							</div>
							<div class="form-group">
                                <div class="input-group">
                                    <?php echo $this->formRow($form->get('content')->setValue( $page->content));?>
								</div>
							</div>
							<div class="form-group">
                                <div class="input-group">
                                     <label>META TITLE</label>
                                    <?php echo $this->formRow($form->get('meta_title')->setValue( $page->meta_title));?>
								</div>
							</div>
							<div class="form-group">
                                <div class="input-group">
                                    <label>META DESCRIPTION</label>
                                    <?php echo $this->formRow($form->get('meta_description')->setValue( $page->meta_description));?>
								</div>
							</div>
							<div class="form-group">
                                <div class="input-group">
                                    <label>META KEYWORDS</label>
                                    <?php echo $this->formRow($form->get('meta_keywords')->setValue( $page->meta_keywords));?>
								</div>
							</div>
							<div class="form-group">
                                <div class="input-group">
                                    <label>ROBOTS</label>
                                    <?php echo $this->formRow($form->get('robots')->setValue($page->robots));?>
								</div>
							</div>
							<div class="form-group">
                                <div class="input-group">
                                   <label>STATUS</label>
                                    <?php echo $this->formRow($form->get('status')->setValue($page->status));?>
								</div>
							</div>
                          
                        
                        
                            <?php echo $this->formRow($form->get('submit')->setValue('Update'));?>
                        
                     <?php echo $this->form()->closeTag();?>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                        </div>
                    </div>

                </section>