<?php
$this->headLink()->prependStylesheet($this->basePath() . '/assets/lib/datepicker/css/datepicker.css');

$this->headScript()->prependFile($this->basePath() . '/assets/lib/datepicker/js/bootstrap-datepicker.js');
?>
  <?= $this->partial('layout/top_links'); ?>
<?php
$title = 'Add new Event';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('memoralize-create-infos'));
$form->prepare();
echo $this->form()->openTag($form);
?>
<div id="step1">
<?php
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('first_name'));
echo $this->formRow($form->get('middle_name'));
echo $this->formRow($form->get('last_name'));
echo $this->formRow($form->get('dob'));
echo $this->formRow($form->get('age'));
echo $this->formRow($form->get('death_place'));
?>
</div>
<div id="step2">
<?php
echo $this->formRow($form->get('education'));
?>
</div>
<div id="step3">
<?php
echo $this->formRow($form->get('family'));
?>
</div>
<?php
echo $this->formRow($form->get('tributes'));
?>
<?php
echo $this->formRow($form->get('privacy'));
?>
<div id="step4">
<?php
echo $this->formRow($form->get('guest_book'));

echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();
?>
 </div>


<?php $this->inlineScript()->captureStart() ?>
$(function() {
  $('.dp').datepicker({
format: 'yyyy-mm-dd'
});
 
});

<?php $this->inlineScript()->captureEnd() ?>