<?php
$this->headLink()->prependStylesheet($this->basePath() . '/assets/lib/plupload/js/jquery.plupload.queue/css/jquery.plupload.queue.css');

$this->headScript()->prependFile($this->basePath() . '/assets/js/main.js')
        ->prependFile($this->basePath() . '/assets/lib/uniform/jquery.uniform.min.js')
        ->prependFile($this->basePath() . '/assets/lib/plupload/js/jquery.plupload.queue/jquery.plupload.queue.min.js')
        ->prependFile($this->basePath() . '/assets/lib/plupload/js/plupload.full.min.js');
?>
  <?= $this->partial('layout/top_links'); ?>
<div id="error"></div>
<form method='post' action=''>
    <div class='memo_images'>
        <ul>
            <?php foreach ($images as $image) { ?>
                <li>
                    <input type="checkbox" name="ids[]" value="<?php echo $image['id']; ?>">
                    <img src="<?php echo $this->basePath('/../module/Memoralize/assets/images/' . $image['image_url']); ?>" width="72" height="72"/>
                    <br>
                    <input type="radio" name="cover" <?php
                    if ($image['main_image'] == 1) {
                        echo 'checked';
                    }
                    ?> value="<?php echo $image['id']; ?>"> Cover Image

                </li>
            <?php } ?>
        </ul>
        <input type='submit' value='Update' class="btn btn-lg btn-default btn-sm"/>
        <input type='hidden' name='action' value='cover'/>
        <a ref='#' id='delete' class="btn btn-lg btn-default btn-sm">Delete</a>
    </div>
</form>
<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <header>
                <h5>Image Uploader</h5>
            </header>
            <div id="collapse2" class="block">
                <form>
                    <div id="uploader"></div>
                </form>
            </div>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="avupload">
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('memoralize-create-media'));

    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
    <div class="player_preview">
        <video width="400" height="200" src="<?php echo $this->basePath('/../module/Memoralize/assets/media/' . $this->media->media_url); ?>" controls>
            Your browser does not support the <code>video</code> element.
        </video>
    </div>
</div>
 <a  href="<?php echo $this->url('memoralize-create',array('step'=>'2','id'=>$this->id))?>"> 
    Complete Step 2
 </a>
<script>

    $(document).ready(function() {
        $('#uploader').pluploadQueue({
            url: '<?php echo $this->basePath('memoralize-step2/upload/' . $this->id); ?>',
            max_files: 2,
            filters: [
                {title: "Image files", extensions: "jpg,gif,png"}
            ],
            rename: true,
            init: {
                FilesAdded: function(up, files) {
                },
                UploadComplete: function(up, files) {
                    // destroy the uploader and init a new one
                    up.destroy();
                    location.reload();

                }
            }
        });


        $("#delete").click(function() {
            event.preventDefault();
            var searchIDs = $(".memo_images input:checkbox:checked").map(function() {
                return $(this).val();
            }).get();
            if (searchIDs.length != 0) {
                var formData = {ids: searchIDs, action: "delete"};
                $.ajax({
                    type: "POST",
                    url: "<?php echo $this->basePath('memoralize-step2'); ?>",
                    data: formData,
                    success: function(result) {
                        location.reload();
                    }});
            } else {
                $("#error").html('Please select images');
            }
        });


    });
</script>
