<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/assets/css/rituals.css'); ?>
<?= $this->partial('layout/top_links'); ?>
<div class="layout_nav">
    <ul>
        <li><a class="before" href="<?php echo $this->basePath('/'); ?>">Home &rsaquo; </a></li>
        <li><a class="before" href="<?php echo $this->url('cremation-plans'); ?>">Cremation Planning &rsaquo;</a></li>
        <li>Donation
    </ul>
</div>
<div class="clear"></div>
<div class="maindonation">
    <h4>Make a Donate</h4>
    <div class="clear"></div>
    <div id="tabs" class="donation">
        <ul>
            <li><a href="#cash"><span>Cash</span></a></li>
            <li><a href="#diseased"><span>Diseased's Possessio</span></a></li>
            <li><a href="#noncash"><span>Other Non Cash Gifts</span></a></li>
            <li><a href="#resource"><span>Resources</span></a></li>
            <li><a href="#mydonation"><span>My Donation</span></a></li>
        </ul>
        <div id="cash"> 
             <h4>This gift is to be made in memory of</h4>
             <h3> <?php echo $this->infos->first_name . ' ' . $this->infos->middle_name . ' ' . $this->infos->last_name; ?></h4>
                <p class="info"><?php echo date('F j, Y'); ?></3>
                     
                <div class="donationimage">
          <?php  
            foreach ($this->garlands as $garland) {
                if ($garland['id'] == $this->infos->garland_id) {
                    ?>

                    <img class="garland" src="<?php echo $this->basePath('/../module/CremationPlan/assets/garland/' . $garland['garland_image']); ?>" width="145" height="177" class="garland"/>

                    <?php
                }
            }
            ?>
                <?php if ($this->type == 'obituary') { ?>

                    <img src="<?php echo $this->basePath('/../module/Obituary/assets/images/' . $this->images->obituary_id . '/' . $this->images->image_url); ?>" width="128" height="140"/>
                <?php } else { ?>
                    <img src="<?php echo $this->basePath('/../module/Memoralize/assets/images/' . $this->images->memoralize_id . '/' . $this->images->image_url); ?>" width="128" height="140"/>

                <?php } ?>
                    </div>
          
            <div class="donateform">
                <form method="POST" action="<?php echo $this->url('donation',array('action'=>'donate','id'=>$this->id,'type'=>$this->type))?>">
                    <p>
                    <select id="cause" name="cause_id">
                        <option value="">Please selcet a cause</option>
                        <?php foreach ($this->cause as $cause) { ?>
                            <option value="<?php echo $cause['id']; ?>"><?php echo $cause['title']; ?></option>
                        <?php } ?>
                    </select>
                    </p><p>
                     <select id="charity" name="charity_id">
                        <option value="">Please selcet a charity</option>
                     </select>
                        </p><p>
                     <select id="amount" name="currency">
                        <option value="USD">USD</option>
                         <option value="INR">INR</option>
                     </select>
                    <input type="text" placeholder="Please enter the amount" value="" name="amount"/>
                        </p>
                        <p>
                            <input type="submit" value="Add to" class="btn btn-danger btn-sm "/>
                        </p>
                </form>
            </div>
        </div>
        <div id="diseased">
            <p>diseased</p>
        </div>
        <div id="noncash">
            <p>noncash</p>
        </div>
        <div id="resource">
            <p>resource</p>
        </div>
        <div id="mydonation">
            <p>mydonation</p>
        </div>
    </div>
    <div class="suggested">
        <h4>Suggested Charities</h4>
        <ul>
            <?php foreach ($this->charities as $charity) { ?>
                <li>
                    <div class="charityimg">
                        <?php if ($charity['photo_url'] != '') { ?>

                            <img src="<?php echo $this->basePath('/../module/Donation/assets/charity/' . $charity['id'] . '/' . $charity['photo_url']); ?>" width="72" height="72"/>
                        <?php } else { ?>
                            <img src="<?php echo $this->basePath('/../module/Donation/assets/charity/no-image.jpg'); ?>" width="72" height="72"/>

                        <?php } ?>
                    </div>
                    <div class="charitydetail">
                        <h4> <?php echo $charity['name']; ?></h4> 
                        <p>
                            <?php echo substr($charity['description'], 0, 80) . '...'; ?>
                            <a href="#charity-<?php echo $charity['id']; ?>" class="fancybox readmore floatright">Read More</a>
                        </p>
                    </div>
                    <div class="clear"></div>
                    <div id="charity-<?php echo $charity['id']; ?>" style="display:none;" class="charity">
                        <h4> <?php echo $charity['name']; ?></h4> 
                        <p style="width:500px">
                            <?php echo $charity['description']; ?>                                     
                        </p>
                        <p>
                            <label>Address : </label><?php echo $charity['address']; ?>                                     
                        </p>
                        <p>
                            <label>Contact Person : </label><?php echo $charity['contact_name']; ?>                                     
                        </p>
                        <p>
                            <label>Website Url : </label><a href="<?php echo $charity['url']; ?>"><?php echo $charity['url']; ?>  </a>                                   
                        </p>
                    </div>
                </li>
            <?php } ?>
        </ul>
    </div>

</div>

<script>
    $(function() {
       
        $("#tabs").tabs();
        $(".fancybox").fancybox();


        $('#cause').change(function() {

            var data = {'cause_id': $(this).val()}
            $.ajax({
                type: 'POST',
                url: '<?php echo $this->url('donation', array('action' => 'charity')); ?>',
                data: data,
                success: function(data) {
                   
                   $( "#charity" ).html(data);
                }
            });

        });

    });
</script>