<?php

// Generated by ZF2's ./bin/classmap_generator.php @ Sun, 15 Jan 2012 19:46:42 -0700
return array(
    'Obituary\Module' => __DIR__ . '/src/Obituary/Module.php',
    'Obituary\Mapper\Infos' => __DIR__ . '/src/Obituary/Mapper/Infos.php',     
    'Obituary\Mapper\InfosInterface' => __DIR__ . '/src/Obituary/Mapper/InfosInterface.php',
    'Obituary\Mapper\Obituary' => __DIR__ . '/src/Obituary/Mapper/Obituary.php',
    'Obituary\Mapper\ObituaryInterface' => __DIR__ . '/src/Obituary/Mapper/ObituaryInterface.php',    
    'Obituary\Mapper\MediaInterface' => __DIR__ . '/src/Obituary/Mapper/MediaInterface.php',
    'Obituary\Mapper\Media' => __DIR__ . '/src/Obituary/Mapper/Media.php',
    
    'Obituary\Controller\InfosController' => __DIR__ . '/src/Obituary/Controller/InfosController.php',
    'Obituary\Controller\IndexController' => __DIR__ . '/src/Obituary/Controller/IndexController.php',
    'Obituary\Controller\MediaController' => __DIR__ . '/src/Obituary/Controller/MediaController.php',
    
    'Obituary\Service\ModuleOptionsFactory' => __DIR__ . '/src/Obituary/Service/ModuleOptionsFactory.php',
    'Obituary\Service\InfosMapperFactory' => __DIR__ . '/src/Obituary/Service/InfosMapperFactory.php',
    'Obituary\Service\ObituaryMapperFactory' => __DIR__ . '/src/Obituary/Service/ObituaryMapperFactory.php',
   
    'Obituary\Options\ModuleOptions' => __DIR__ . '/src/Obituary/Options/ModuleOptions.php',
    
    'Obituary\Entity\Infos' => __DIR__ . '/src/Obituary/Entity/Infos.php',
    'Obituary\Entity\InfosInterface' => __DIR__ . '/src/Obituary/Entity/InfosInterface.php',
    'Obituary\Entity\Obituary' => __DIR__ . '/src/Obituary/Entity/Obituary.php',
    'Obituary\Entity\ObituaryInterface' => __DIR__ . '/src/Obituary/Entity/ObituaryInterface.php',
    'Obituary\Entity\Media' => __DIR__ . '/src/Obituary/Entity/Media.php',
    'Obituary\Entity\MediaInterface' => __DIR__ . '/src/Obituary/Entity/MediaInterface.php',
);