<?php
$this->headScript()->prependFile($this->basePath() . '/assets/lib/NicEditor/nicEdit.js');
 ?>
<div id="top"><?= $this->partial('layout/admin_top_menu', array('tittle' => 'Add PrePlanning')); ?></div>
<div id="left"> <?= $this->partial('layout/left-menu', array('preplanning' => 'active')); ?></div> 
<div id="content"> 
    <div class="outer">
        <div class="inner">
            <h4>Add New Plan</h4>
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('admin/pre-planning', array('action' => 'add','category'=>$this->category)));           
            $form->prepare();
            echo $this->form()->openTag($form);
            echo $this->formCollection($form);
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>
<?php $this->inlineScript()->captureStart() ?>
$(function() {  nicEditors.allTextAreas(); });
<?php $this->inlineScript()->captureEnd() ?>