
<?php
$this->headScript()->prependFile($this->basePath() . '/assets/js/main.js')
        ->prependFile($this->basePath() . '/assets/lib/touch-punch/jquery.ui.touch-punch.min.js')
        ->prependFile($this->basePath() . '/assets/lib/tablesorter/js/jquery.tablesorter.min.js')
        ->prependFile($this->basePath() . '/assets/lib/datatables/DT_bootstrap.js')
        ->prependFile($this->basePath() . '/assets/lib/datatables/jquery.dataTables.js');
?>
<div id="top"><?= $this->partial('layout/admin_top_menu', array('tittle' => 'PrePlanning List')); ?></div>
<div id="left"> <?= $this->partial('layout/left-menu', array('preplanning' => 'active')); ?></div> 
<div id="content"> 
    <div class="outer">
        <div class="inner">
            <!--/span-->
            <div class="row">
                <div class="col-lg-12">
                    <div class="box">
                        <header> 
                            <h5><?php  echo $this->item->title;?> Check List</h5>
                        </header>
                        <div id="collapse4" class="body">
                            <form name="dataform" method="POST" action="">
                                <div class="action">                                    
                                    <select name="action" class="form-control">
                                        <option value="">Select Action</option>
                                        <option value="multidelete">Delete</option>                                        
                                    </select>
                                    <input type="submit" value="Submit" class="btn btn-default btn-sm"/>
                                </div>
                                <table id="dataTable" class="table ">
                                    <thead>
                                        <tr>
                                            <th><input type="checkbox" name="sellectall" value="" ></th>
                                            <th>Title </th> 
                                              <th><a class="btn btn-default btn-sm floatright" href="<?php echo $this->url('admin/pre-planning', array('action' => 'addchecklist','category'=>$this->category,'id'=>$this->id)); ?>">Add Check List</a></th> 
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->paginator as $data) : ?>
                                            <tr>
                                                <td>

                                                    <input type="checkbox" class="case" name="ids[]" value="<?php echo $data->id ?>"></td>
                                                <td>


                                                    <p><?php echo $this->escapeHtml($data->title); ?></p>                                                      
                                                </td>
                                                <td>
                                                    <a title="Edit List" href="<?php echo $this->url('admin/pre-planning', array('action' => 'editchecklist','category'=>$this->category, 'id' => $data->id));
                                            ?>"><i class="fa fa-pencil fa-fw"></i></a>
                                                    <a title="Delete List" href="<?php echo $this->url('admin/pre-planning', array('action' => 'deletechecklist','category'=>$this->category, 'id' => $data->id));
                                            ?>"><i class="fa fa-trash-o fa-fw"></i></a>
                                                    </div>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </form>
                        </div></div>
                </div>
                <!--/row-->
            </div>
            <!--/span-->
        </div>
        <!--/row-->
    </div>
    <?php $this->inlineScript()->captureStart() ?>
    $(function() { metisTable(); metisSortable();});
    <?php $this->inlineScript()->captureEnd() ?>

</div> 
