<div id="top"><?= $this->partial('layout/admin_top_menu', array('tittle' => 'Edit Category')); ?></div>
<div id="left"> <?= $this->partial('layout/left-menu', array('category' => 'active')); ?></div> 
<div id="content"> 
    <div class="outer">
        <div class="inner">

            <?php
            $form = $this->form;
            $form->setAttribute('action', 
                    $this->url('admin/preplanning-links', array('action' => 'edit','category'=>$this->category,'id' => $this->id)));
            $form->prepare();

            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id'));
            echo $this->formHidden($form->get('preplanning_id'));
            echo $this->formRow($form->get('category'));            
            echo $this->formRow($form->get('title'));   
            echo $this->formRow($form->get('url')); 
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>