<div id="top"><?= $this->partial('layout/admin_top_menu', array('tittle' => 'Edit Charity')); ?></div>
<div id="left"> <?= $this->partial('layout/left-menu', array('donation' => 'active')); ?></div> 
<div id="content"> 
    <div class="outer">
        <div class="inner">

            <?php
            $form = $this->form;
            $form->setAttribute('action', 
                    $this->url('admin/donation-charity', array('action' => 'edit','id' => $this->id)));
            $form->prepare();

            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id'));            
            echo $this->formRow($form->get('cause_id'));    
            echo $this->formRow($form->get('name'));  
            echo $this->formRow($form->get('description')); 
            echo $this->formRow($form->get('address')); 
            echo $this->formRow($form->get('contact_name'));
            echo $this->formRow($form->get('url'));
          
              echo $this->formFile($form->get('photo_url'));
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>