<?php

// Generated by ZF2's ./bin/classmap_generator.php @ Sun, 15 Jan 2012 19:46:42 -0700
return array(
    'Memoralize\Module' => __DIR__ . '/src/Memoralize/Module.php',
    'Memoralize\Mapper\Infos' => __DIR__ . '/src/Memoralize/Mapper/Infos.php',     
    'Memoralize\Mapper\InfosInterface' => __DIR__ . '/src/Memoralize/Mapper/InfosInterface.php',
    'Memoralize\Mapper\Memoralize' => __DIR__ . '/src/Memoralize/Mapper/Memoralize.php',
    'Memoralize\Mapper\MemoralizeInterface' => __DIR__ . '/src/Memoralize/Mapper/MemoralizeInterface.php',    
    'Memoralize\Mapper\MediaInterface' => __DIR__ . '/src/Memoralize/Mapper/MediaInterface.php',
    'Memoralize\Mapper\Media' => __DIR__ . '/src/Memoralize/Mapper/Media.php',
    
    'Memoralize\Controller\InfosController' => __DIR__ . '/src/Memoralize/Controller/InfosController.php',
    'Memoralize\Controller\IndexController' => __DIR__ . '/src/Memoralize/Controller/IndexController.php',
    'Memoralize\Controller\MediaController' => __DIR__ . '/src/Memoralize/Controller/MediaController.php',
    
    'Memoralize\Service\ModuleOptionsFactory' => __DIR__ . '/src/Memoralize/Service/ModuleOptionsFactory.php',
    'Memoralize\Service\InfosMapperFactory' => __DIR__ . '/src/Memoralize/Service/InfosMapperFactory.php',
    'Memoralize\Service\MemoralizeMapperFactory' => __DIR__ . '/src/Memoralize/Service/MemoralizeMapperFactory.php',
   
    'Memoralize\Options\ModuleOptions' => __DIR__ . '/src/Memoralize/Options/ModuleOptions.php',
    
    'Memoralize\Entity\Infos' => __DIR__ . '/src/Memoralize/Entity/Infos.php',
    'Memoralize\Entity\InfosInterface' => __DIR__ . '/src/Memoralize/Entity/InfosInterface.php',
    'Memoralize\Entity\Memoralize' => __DIR__ . '/src/Memoralize/Entity/Memoralize.php',
    'Memoralize\Entity\MemoralizeInterface' => __DIR__ . '/src/Memoralize/Entity/MemoralizeInterface.php',
    'Memoralize\Entity\Media' => __DIR__ . '/src/Memoralize/Entity/Media.php',
    'Memoralize\Entity\MediaInterface' => __DIR__ . '/src/Memoralize/Entity/MediaInterface.php',
);