<?php
$this->headLink()->prependStylesheet($this->basePath() . '/assets/lib/plupload/js/jquery.plupload.queue/css/jquery.plupload.queue.css')
         ->prependStylesheet($this->basePath() . '/assets/player/video-js.css');

$this->headScript()->prependFile($this->basePath() . '/assets/js/main.js')
        ->prependFile($this->basePath() . '/assets/lib/uniform/jquery.uniform.min.js')
        ->prependFile($this->basePath() . '/assets/lib/plupload/js/jquery.plupload.queue/jquery.plupload.queue.min.js')
        ->prependFile($this->basePath() . '/assets/lib/plupload/js/plupload.full.min.js')
        ->prependFile($this->basePath() . '/assets/player/video.js');
?>
<?= $this->partial('layout/top_links'); ?>
<div class="layout_nav">
    <ul>
        <li><a class="before" href="<?php echo $this->basePath('/'); ?>">Home &rsaquo; </a></li>
        <li><a class="before" href="<?php echo $this->url('cremation-plans'); ?>">Cremation Planning &rsaquo;</a></li>
        <li><a class="before" href="<?php echo $this->url('obituary'); ?>">Obituary &rsaquo;</a></li>
        <li>Step 2 </li> 
    </ul>
</div>
<div class="clear"></div>

<div class="meadiamain">
    <?php if (count($this->images) > 0) { ?>
        <form method='post' action='' id="profileimage">
            <div class='memo_images'>
                <h4>Images</h4>
                <ul>
                    <?php foreach ($this->images as $image) { ?>
                        <li>
                            <input type="checkbox" name="ids[]" value="<?php echo $image['id']; ?>">
                            <img src="<?php echo $this->basePath('/../module/Obituary/assets/images/'.$image['obituary_id'].'/thumb/' . $image['image_url']); ?>" width="72" height="72"/>
                            <br>
                            <input type="radio" class="pcover" name="cover" <?php
                            if ($image['main_image'] == 1) {
                                echo 'checked';
                            }
                            ?> value="<?php echo $image['id']; ?>"> Cover Image

                        </li>
                    <?php } ?>
                </ul>
                <div class="actions">
                    <input type='submit' value='Update' class="btn btn-lg btn-default btn-sm"/>
                    <input type='hidden' name='action' value='cover'/>
                    <input type='hidden' name='step' value="<?php echo $this->step; ?>"/>
                    <a ref='#' id='delete' class="btn btn-lg btn-default btn-sm ">Delete</a>
                </div>
            </div>
        </form>
    <?php } ?>
    <?php if (count($this->garlands) > 0) { ?>
        <form method='post' action='' id="garlandform">
            <div class='memo_images'>
                <h4>Garlands</h4>
                <ul>
                    <?php foreach ($this->garlands as $image) { ?>
                        <li>                           
                            <img src="<?php echo $this->basePath('/../module/CremationPlan/assets/garland/thumb/' . $image['id'] . '_' . $image['garland_image']); ?>" width="72" height="72"/>
                            <br>
                            <input type="radio" class="icover" name="cover" <?php
                            if (isset($this->infos->garland_id)) {
                                if ($image['id'] == $this->infos->garland_id) {
                                    echo 'checked';
                                }
                            }
                            ?> value="<?php echo $image['id']; ?>"> Garland Image

                        </li>
                    <?php } ?>
                </ul>
                <div class="actions">
                    <input type='submit' value='Update' class="btn btn-lg btn-default btn-sm"/>
                    <input type='hidden' name='action' value='garland'/>
                    <input type='hidden' name='step' value="<?php echo $this->step; ?>"/>
                    <input type='hidden' name='id' value='<?php echo $this->id; ?>'/>                
                </div>
            </div>
        </form>
    <?php } if (count($this->images) <= 9) { ?>
        <div class="row">
            <h4>Image Uploader</h4>
            <div class="col-lg-12">
                <div class="box">
                    <div id="collapse2" class="block">
                        <form>
                            <div id="uploader"></div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>
    <?php } ?>
    <div class="avupload">
        <h4>Video Upload</h4>
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('obituary-create-media', array('step', $this->step)));

        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formCollection($form);
        ?>
        <input type='hidden' name='step' value="<?php echo $this->step; ?>"/>
        <?php
        echo $this->form()->closeTag();
        ?>
        <div class="clear:both" style="padding:6px;"></div>
        <?php if (isset($this->media->media_url) && $this->media->media_url != '') { ?>
            <div class="player_preview">
                   <video class="video-js vjs-default-skin" controls preload="none" width="640" height="264"                           
                           data-setup="{}">
                        <source src="<?php echo $this->basePath('/../module/Obituary/assets/media/'.$this->media->obituary_id.'/'. $this->media->media_url); ?>" type='video/mp4' />  
                    </video>
            </div>
        <?php } ?>
    </div>
    <div class="meadiafooter">
        <?php if ($this->step != 0 && count($this->images) > 0) { ?>
            <a  href="<?php echo $this->url('obituary-create-themes', array('step' => '2', 'id' => $this->id)) ?>"> 
                Complete Step 2 >
            </a>
        <?php } else if (count($this->images) > 0) { ?>
            <a  href="<?php echo $this->url('obituary', array('id' => $this->id)) ?>"> 
                < Go to Profile
            </a>
        <?php } ?>
    </div>
</div>

<script>

    $(document).ready(function() {
        
        videojs.options.flash.swf = "video-js.swf";
        
        $('#uploader').pluploadQueue({
            url: '<?php echo $this->basePath('obituary-step2/upload/' . $this->id); ?>',
            max_files: 2,
            max_file_count: 9,
            filters: [
                {title: "Image files", extensions: "jpg,gif,png,jpeg"}
            ],
            rename: true,
            init: {
                FilesAdded: function(up, files) {
                },
                UploadComplete: function(up, files) {
                    // destroy the uploader and init a new one
                    up.destroy();
                    location.reload();

                }
            }
        });


        $("#delete").click(function(event) {
            event.preventDefault();
            var searchIDs = $(".memo_images input:checkbox:checked").map(function() {
                return $(this).val();
            }).get();
            if (searchIDs.length != 0) {
                var formData = {ids: searchIDs, action: "delete"};
                $.ajax({
                    type: "POST",
                    url: "<?php echo $this->basePath('obituary-step2'); ?>",
                    data: formData,
                    success: function(result) {
                        location.reload();
                    }});
            } else {
                alert('Please select images');
            }
        });
        $('input:file').change(
                function() {
                    if ($(this).val()) {
                        $('input:submit').attr('disabled', false);
                        // or, as has been pointed out elsewhere:
                        // $('input:submit').removeAttr('disabled'); 
                    }
                }
        );
    });



    $("#garlandform").submit(function(event) {
         if($('.icover').is(':checked')) {

            return true;
        }
        event.preventDefault();
        alert('Please select any garland image')
    });
    
      $("#profileimage").submit(function(event) {
         if($('.pcover').is(':checked')) {

            return true;
        }
        event.preventDefault();
        alert('Please select any cover image')
    });
    
    
</script>
